### ISSUE TITLE
Modify `get_paper_by_doi` to reflect local file path

### ISSUE THREAD

**Issue by enoriega** [ml4ai/ASKEM-TA1-Demo-2022-10#2]
The path on the cell reflects @enoriega's file system. We have to make sure it points to the correct location where the TR api is running at the time of the demo

**Comment by enoriega** [comment]
@cl4yton tagging you here because I don't have permissions to assign the issue to either of us

**Comment by adarshp** [comment]
@enoriega  - are you sure? It says [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users) that "Anyone with write access to a repository can assign issues and pull requests."

**Comment by adarshp** [comment]
@enoriega - sorry, nevermind, my mistake, I was thinking about the ml4ai/skema repo...
